config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/contact',  to: 'messages#new'
  post '/contact',  to: 'messages#create'
  get  '/sponsors',    to: 'static_pages#sponsors'
  get  '/about',    to: 'static_pages#about'
  get  '/sitemap.xml',    to: 'static_pages#sitemap'

  resources :messages, only: [:new, :create]
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :content
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX }
  validates :subject, presence: true, length: { maximum: 300 }
  validates :content, presence: true
end

                   # attribute :name,      :validate => true
                   # attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
                   # attribute :message
                   # attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
                   # def headers
                   #   {
                     #     :subject => "My Contact Form",
                   #    :to => "your_email@example.org",
                      #    :from => %("#{name}" <#{email}>)
                    #  }
                   # end
#end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def new
    @message = Message.new
  end

  def create 
    @message = Message.new(message_params)


    if @message.valid?
      MessageMailer.send_message(@message).deliver_now
      flash[:success] = "Thank you for your message!"
      redirect_to new_message_path
    else
      render :new 
    end      
  end


private

  def message_params
    params.require(:message).permit(:name, :email, :subject, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def sponsors
  end

  def about
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="padding:10px">
  <small>
  </small>
  <nav>
    <ul class="fooul"  style="font-size:13px">
      <a><u><b>Created and Curated by :</b></u></a></br>SUVIGYA NIJHAWAN<a href="https://github.com/suvi7896" target="_blank">
        <i class="fa fa-github fa-2x socic" aria-hidden="true"></i></a>
        <a href="https://www.linkedin.com/in/suvigya-nijhawan-62330aa7/" target="_blank">
        <i class="fa fa-linkedin-square fa-2x socic" aria-hidden="true">
         </i></a>

        <br />
        SONAM TSHERING &nbsp;
      <a href="https://github.com/sonamtshering1328" target="_blank">
        <i class="fa fa-github fa-2x socic" aria-hidden="true"></i></a>


      <br />



      <p style="font-size: 11px;">


        For Website Enquiries,<br />
        Please Contact :<br/>

        <a href="mailto:suvigyanijhawan@dtu.ac.in">suvigyanijhawan@dtu.ac.in</a>
        <br />
        <a href="mailto:sonamtshering@dtu.ac.in">sonamtshering@dtu.ac.in</a>

      </p>



      <p style="font-size: 12px;">© 2017 All rights reserved - Team Raftaar DTU</p>


      </li>


    </ul>


    <ul class="footul" style="font-size:14px">
      <li class="footli"><a><u><b>Connect with us at :</b></u></a> <br /> <a href="https://facebook.com/RaftaarDTU" target="_blank">
       <p align="center">
        <i class="fa fa-facebook-square fa-5x socic" aria-hidden="true">
        </i></a></li></p>

    </ul>
  <p align="left" style="font-size:12px">
    <u><b>OUR ADDRESS</b></u>
    <br/>
    <br />
    Turbo M/C Laboratory<br />
    WIND TUNNEL<br />
    DELHI TECHNOLOGICAL UNIVERSITY<br/>
    SHAHBAD DAULATPUR, BAWANA ROAD,DELHI-110042<br/>
    <br />
    <a href="mob:+91-9911183431">Aradhya Shandilya - +91 - 99111 83431</a></br>
    <a href="mob:+91-9718138011">Akash Agrawal - +91 - 97181 38011</a>
  </p>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-default" style="background-color:white">
      <div class="container">      
        <%= link_to image_tag("rafci.png",:class => 'rafc'), root_path, class: "logo" %>
        <%= link_to image_tag("raft.png",:class => 'rafte'), root_path, class: "logo" %>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item hea"><%= link_to "HOME",   root_path %></li>
            <li class="nav-item hea"><%= link_to "ABOUT US",   about_path %></li>
            <li class="nav-item hea"><%= link_to "SPONSORS", sponsors_path%></li>
            <li class="nav-item hea"><%= link_to "CONTACT", contact_path%></li>
          </ul>
        </div>

      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=>'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=>'reload' %>
    <%= render 'layouts/shim' %>

    <meta name="google-site-verification" content="zcTtjdC1OH8inJ5lwBoHltmtSLtR8yPS8AfGlqRNnH0" />
    <meta name="google-site-verification" content="UcCARJhWxetD-Jd12eXNsnKtb7PNbN7zeL5bwNKAeio" />
  </head>
  <body>
    <%= render 'layouts/header' %>
       <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>

<div class="row scro">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@message, url: contact_path) do |f| %>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@message.errors.count, "error") %>.
        </div>
        <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="container">
      <div class="pull-left">
      <div class="col-md-12" style="margin:8px">
        <contact class="contact">
        <b>Mobile:</b> &nbsp;

        <a href="mob:+91-9911183431"> Aradhya Shandilya - +91 - 99111 83431</a></br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="mob:+91-9718138011">Akash Agrawal - +91 - 97181 38011</a></br>


        <br/>
        <b>Email:</b> <a href="mailto:teamraftaar@dtu.ac.in">teamraftaar@dtu.ac.in</a>
        <br/>
        <br/>
        <b>Faculty Advisor : </b><br/>
        Dr. Rajesh Kumar<br/>
          Department of Mechanical, Production and Automobile Engineering<br/>
          Delhi Technological University<br/>
          Shahbad Daulatpur, Delhi-110042<br/>
          Mob :   <a href="mob:++91-8750632739">+91-8750632739</a><br/>
          Email : <a href="mailto:dr.rajeshmits@gmail.com">dr.rajeshmits@gmail.com</a><br/>
        </contact>
      </div>
      </div>
     </div>
     </br>
     <p><em>Leave a message below and we will respond shortly.</em></p></br>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :subject %>
      <%= f.text_field :subject, class: 'form-control' %>

      <%= f.label :content, "Message" %>
      <%= f.text_area :content, :rows => "5", class: 'form-control' %>

      <%= f.submit "Send Message", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/static_pages/about.html.erb
<div style="margin-bottom:10px">

<% provide(:title, "About") %>

<%= image_tag 'team.jpg', :class => "img-responsive center-block" %>

</div>
<div class="container">
  <div class=".center">
    <p style="text-align:center">
    <br />

      <div class="col-md-4 ab">
        <h1>ASME HPVC</h1>

        <p align="center">Human-powered transport is often the only type available in underdeveloped or inaccessible parts of the world, and if well designed, can be an increasingly viable form of sustainable transportation.
          ASME's international Human Powered Vehicle Challenge (HPVC) provides an opportunity for students to demonstrate application of sound engineering design principles in the development of sustainable and practical transportation alternatives.In the HPVC, students work in teams to design and build highly
          engineered vehicles for everyday common use—from commuting to work to market.</p>
      </div>
      <div class="col-md-4 ab">
        <h1>D.T.U.</h1>
        <p align="center">Formerly known as the Delhi College of Engineering (under Delhi University), Delhi Technological University is India's leading institutes for technical
          education and research. Established in 1941, Delhi Technological University has grown to become a pioneer in the field of research and innovation right down
          to the undergraduate levels. It is also considered to be the mother institute of Indian Institute of Technology, Delhi and the Netaji
          Subhash Institute of Technology. It is known for its culture of incubating Mechanica Tech Teams.
          Team Raftaar is one of the most successful teams at DTU.</p>
      </div>
      <div class="col-md-4 ab">
        <h1>Team Raftaar</h1>
        <p align="center">We are a team of undergraduate students of Delhi Technological University ( Formerly DCE ) who have taken up the challenge to design and develop a Human Powered Vehicle (HPV) for the ASME HPVC - 2017. We are the only HPV team that has represented India in ASME WEST, held in California, USA (2016).
          With an improved design and better equipment we already are on the driver's seat to lay benchmarks at Indian and International events.
          Our vehicle supports green energy and is capable of blending into our lifestyles. In the coming years, this HPV concept could really be a profitable venture.
        </p>
      </div>

    <!--<%= image_tag 'freechildcare.png', :class => "img-responsive center-block"%>-->
  <p align="center">
    <a href="https://www.paypal.me/krishangupta" target="_blank"><button type="button" class="don btn btn-warning">DONATE</button></a>
  </p>

  </div>
</div>


  

app/views/static_pages/forms.html.erb
<% provide(:title, "Sponsors") %>
    <h1>Sponsors</h1>

<div class="container">
  <div class="col-md-4 sp">
    <%= image_tag 'Decathlon_Logo.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'vactech.jpg', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'asme-logo.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'BTWIN2.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'fir_logo.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'atcon.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'krystal.jpg', :class => "img-responsive center-block" %>

  </div>


</div>

    <h2>
      For Further Details , Click to open: <%= link_to "Sponsorship Brochure", asset_path("corporate brochure 2016-17.pdf"), target: :_blank %>
    </h2>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 style="color:black">&nbsp;</h1>
  <h2 style="color:white">&nbsp;&nbsp;</h2>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>



  <%= link_to 'Contact Us', contact_path, :class => "cont btn btn-primary btn-lg"%>
</div>

<!--<div class="container" style="background-color:#99c5f6">
  <div class="col-md-12">
  <br/>
    <h1 style="color:black"><b>Our Programs</b></h1> <br/>
    <div class="pull-left"><img class="img-responsive" alt: "crayons pic" src="/assets/crayons.png" id="homepic"></div>
    <div class="pull-left"><h2 style="color:white">Your Infant's Developmental Area</h2>
    <ul>
      <li>Creative Expression</li>
      <li>Cognitive Development</li>
      <li>Physical Development and Wellness</li>
      <li>Soical and Emotional Development</li>
      <li>Executive Function</li>
      <li>Language and Literacy Development</li>
    </ul>
  
    <h2 style="color:white">Your Toddler's Developmental Area</h2>
    <ul>
      <li>Language and Literacy Development</li>
      <li>Executive Function</li>
      <li>Social and Emotional Development</li>
      <li>Physical Development and Wellness</li>
      <li>Cognitive Development</li>
      <li>Creative Expression</li>
    </ul>
  </div>
</div>
</div>-->


  <div class="col-md-12 tl">
  <div class="page-header">
    <h1 id="timeline">Timeline</h1>
  </div>
  <ul class="timeline">
    <li>
      <div class="timeline-badge"><i class="fa fa-trophy" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">2017 - HPVC Asia Pacific</h4>
          <!--<p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 11 hours ago via Twitter</small></p>-->
        </div>
        <div class="timeline-body">
          <p><ul type="disc"><li>1st Rank overall, HPVC-Asia Pacific</li></ul> </p>
        </div>
      </div>
    </li>
    <li class="timeline-inverted">
      <div class="timeline-badge warning"><i class="fa fa-star" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">2017 - HPVC Asia Pacific </h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>1st in Design</li>
          <li>1st in Men's Speed Event</li>
          <li>1st in Women's Speed Event</li>
        </ul></p>
        </div>
      </div>
    </li>

    <li>
      <div class="timeline-badge danger"><i class="fa fa-car" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">MACH4</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Human Powered Vehicle for 2017</li>
        </ul></p>
        </div>
      </div>
    </li>

    <li class="timeline-inverted">
      <div class="timeline-badge warning"><i class="fa fa-star" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">2016 - HPVC West</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>First Indian Team to participate in HPVC West.</li>
          <li>Rank 12th in Design Event.</li>
        </ul> </p>

        </div>
      </div>
    </li>

    <li>
      <div class="timeline-badge success"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">HPVC WEST, California , U.S.A</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Only Team from India to participate.</li>
        </ul></p>
        </div>
      </div>
    </li>


    <li class="timeline-inverted">
      <div class="timeline-badge danger"><i class="fa fa-car" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">PEGASUS</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Human Powered Vehicle for 2016</li>
        </ul></p>
        </div>
      </div>
    </li>


    <li>
      <div class="timeline-badge"><i class="fa fa-trophy" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">2015 ASME-HPVC India</h4>
          <!--<p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 11 hours ago via Twitter</small></p>-->
        </div>
        <div class="timeline-body">
          <p><ul type="disc"><li>Secured 1st Position Overall.</li></ul> </p>
        </div>
      </div>
    </li>

    <li class="timeline-inverted">
      <div class="timeline-badge warning"><i class="fa fa-star" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">2015 ASME-HPVC India</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>1st in the Design Event.</li>
          <li>Clocked the fastest time in sprint race.</li>
        </ul> </p>

        </div>
      </div>
    </li>

    <li>
      <div class="timeline-badge danger"><i class="fa fa-car" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">NIMBUS</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Human Powered Vehicle for 2015</li>
          <li>Fastest HPV in India.</li>
          <li>Top speed of 67 kmph.</li>
        </ul></p>
        </div>
      </div>
    </li>

    <li class="timeline-inverted">
      <div class="timeline-badge warning"><i class="fa fa-star" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">2014 HPVC India</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Debut at IIT-Delhi.</li>

        </ul> </p>

        </div>
      </div>
    </li>

    <li >
      <div class="timeline-badge danger"><i class="fa fa-car" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">VECHICLE-I</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Human Powered Vehicle for 2014</li>
        </ul></p>
        </div>
      </div>
    </li>

    <li class="timeline-inverted">
      <div class="timeline-badge info"><i class="fa fa-leaf" aria-hidden="true"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title">ESTABLISHED</h4>
        </div>
        <div class="timeline-body">
          <p><ul type="disc">
          <li>Team Raftaar DTU founded at DTU in 2014.</li>
        </ul></p>
        </div>
      </div>
    </li>

  </ul>
  </div>

app/views/static_pages/sponsors.html.erb
<% provide(:title, "Sponsors") %>
    <h1>Sponsors</h1>

<div class="container">
  <div class="col-md-4 sp">
    <%= image_tag 'Decathlon_Logo.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'vactech.jpg', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'asme-logo.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'BTWIN2.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'fir_logo.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'atcon.png', :class => "img-responsive center-block" %>

  </div>

  <div class="col-md-4 sp">
    <%= image_tag 'krystal.jpg', :class => "img-responsive center-block" %>

  </div>


</div>

    <h2>
      For Further Details , Click to open: <%= link_to "Sponsorship Brochure", asset_path("corporate brochure 2016-17.pdf"), target: :_blank %>
    </h2>